name: asdaf_training_one
# channels priority
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - matplotlib
  - jupyterlab=2
  - nodejs
  - nbresuse
  - psutil
  - pip
  
